name: Docker Build & Push (Volatility2 Alpine)

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/**'
      - '**.sh'
      - '**.py'
      - '**.conf'
      - '**.yml'

jobs:
  build-and-push:
    name: Build and Push Volatility2 Alpine Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Volatility2 Alpine image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  
          push: true
          tags: quasitiger/volatility2:alpine

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
